language: node_js

node_js:
    - '10'

cache:
    directories:
        - node_modules

notifications:
    email:
        - tom.wilberding@alphapoint.com
        - zach.lysobey@alphapoint.com

before_script:
    - npm run startGanache

script:
    - npm run test

after_script:
    - npm run stopGanache

deploy:
    provider: npm
    email: zach.lysobey@alphapoint.com
    api_key: $AP_NEXUS_API_KEY
    skip_cleanup: true
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^master|hotfix-.*$
